### ISSUE TITLE
getting  invalid rex file and The designer could not be shown for this file because none of the classes within it can be designed. 

### ISSUE THREAD

**Issue by therollingbird** [ArsenAbazian/CryptoTradingFramework#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Invalid Resx file. Type DevExpress.Utils.Svg.SvgImage, DevExpress.Data.v19.1, Version=19.1.0.0, Culture=neutral, PublicKeyToken=79868b8147b5eae4 in the data at line 124, position 4 cannot be located. Line 143, position 5.	Crypto.UI	D:\Visual Studio Programmes\CryptoTradingFramework-master(1)\CryptoTradingFramework-master\Crypto.UI\Controls\ChartDataControl.resx	143	
![Capture3](https://user-images.githubusercontent.com/35991749/61697058-dbb17900-ad79-11e9-9279-b521f36792be.PNG)
![Capture4](https://user-images.githubusercontent.com/35991749/61697116-fa177480-ad79-11e9-8e01-1aeae8a6631c.PNG)

**Comment by ArsenAbazian** [comment]
Hi, my application uses the DevExpress WinForms library for UI. So to make possible to design forms, you need to install it from the https://go.devexpress.com/devexpressdownload_universaltrial.aspx manually. I  cannot publish them here because it is not free.
