### ISSUE TITLE
Can't find WebApplication1.csproj file

### ISSUE THREAD

**Issue by iviss** [ArsenAbazian/CryptoTradingFramework#2]
Try to run your script ,but docker show error: 

COPY failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder283140821\WebApplication1\WebApplication1.csproj: The system cannot find the file specified.
 
Maybe I do something wrong...

**Comment by ArsenAbazian** [comment]
Hi, Sorry for delayed response - I did not notice your issue. Could you please tell me, what goal you are trying to achive? This unfinished app only shows classic arbitrage possibilities between poloniex and bittrex. It was actual some time ago, but now it is useless. And as I remember I didn't use docker for this app. I'll try to fix this in a future.
