### ISSUE TITLE
Create a fresh release so we able to use as we don't have compiler for some reason

### ISSUE THREAD

**Issue by coolerspeex** [ArsenAbazian/CryptoTradingFramework#21]

**Comment by ArsenAbazian** [comment]
Hi, I want to notify you that this project is still under development and used as a base for experiments. I will publish fresh release after 27 august. Now I do not have possibilities to do that.

**Comment by coolerspeex** [comment]
Hey, 27 August you said for release i still waiting

**Comment by coolerspeex** [comment]
@ArsenAbazian bro waiting for fresh release

**Comment by ArsenAbazian** [comment]
Hi,

https://github.com/ArsenAbazian/CryptoTradingFramework/releases/tag/1.06
I believe that you use it for just playing. ;) 

Thanks,
Arsen.
